Repository openhab/openhab-jruby, pull requests merged in 2023-05, with the labels that each got.

#68 Support regexes for from/to/command filters on triggers
  lib/openhab/dsl/rules/builder.rb
  lib/openhab/dsl/rules/rule_triggers.rb
  lib/openhab/dsl/rules/triggers/changed.rb
  lib/openhab/dsl/rules/triggers/command.rb
  lib/openhab/dsl/rules/triggers/conditions.rb
  lib/openhab/dsl/rules/triggers/conditions/duration.rb
  lib/openhab/dsl/rules/triggers/conditions/generic.rb
  lib/openhab/dsl/rules/triggers/conditions/proc.rb
  lib/openhab/dsl/rules/triggers/updated.rb
  spec/openhab/dsl/rules/builder_spec.rb
Labels: enhancement

#69 Fix duration trigger conditions for group member triggers
  lib/openhab/dsl/rules/triggers/conditions/duration.rb
  spec/openhab/dsl/rules/builder_spec.rb
Labels: bug

#70 Update version number in the installation instructions
  Rakefile
  USAGE.md
Labels: documentation

#73 Add unit argument to items builder
  .github/workflows/ci.yml
  USAGE.md
  lib/openhab/dsl/items/builder.rb
  spec/openhab/core/items/number_item_spec.rb
  spec/openhab/core/items/persistence_spec.rb
  spec/openhab/core/types/quantity_type_spec.rb
  spec/openhab/dsl/items/builder_spec.rb
  spec/openhab/dsl/items/ensure_spec.rb
Labels: enhancement

#74 Workaround unusual inheritance chain of `main`
  lib/openhab/core_ext/ruby/object.rb
  lib/openhab/dsl.rb
Labels: bug
