Repository openhab/openhab-jruby, pull requests merged in 2023-08, with the labels that each got.

#108 s/next.openhab.org/www.openhab.org/g
  docs/examples.md
Labels: documentation

#94 Fix loading a console session of your own openHAB instance
  docs/testing.md
  lib/openhab/rspec.rb
Labels: bug

#105 Support all_states_since and all_states_between persistence methods
  lib/openhab/core/items/persistence.rb
  spec/openhab/core/items/persistence_spec.rb
Labels: enhancement

#95 Add timeout during karaf boot process waits
  lib/openhab/rspec/karaf.rb
Labels: bug

#109 Fix example for .profile
  lib/openhab/dsl.rb
Labels: documentation

#112 Add string interpolation and methods
  docs/ruby-basics.md
Labels: documentation

#110 Add callback to .profile yield param docs
  lib/openhab/dsl.rb
Labels: documentation

#113 Change addon's readme images to `doc/`
  templates/default/layout/markdown/setup.rb
Labels: documentation

#114 Change base link in USAGE.md regenerate instruction
  Rakefile
  USAGE.md
Labels: documentation

#116 Fix block passing in Hash#delete_if
  lib/openhab/core/items/metadata/hash.rb
Labels: bug

#118 Minor corrections in documentation on timers and shared_cache
  USAGE.md
  lib/openhab/core/value_cache.rb
Labels: documentation

#117 Fix doc references to Core::Timer
  lib/openhab/dsl/timer_manager.rb
Labels: documentation

#120 Add SemanticTag#to_s
  lib/openhab/core/items/semantics.rb
  lib/openhab/core/items/semantics/semantic_tag.rb
  lib/openhab/dsl/items/builder.rb
  spec/openhab/core/items/semantics_spec.rb
Labels: enhancement

#111 Don't tag `cron`, `every`, and `at` triggers with "Schedule"
  lib/openhab/dsl/rules/builder.rb
  spec/openhab/dsl/rules/builder_spec.rb
Labels: enhancement

#123 Add `event.inputs`; and `event.group` attributes for triggeringGroup
  USAGE.md
  lib/openhab/core/events/abstract_event.rb
  lib/openhab/core/events/item_event.rb
  lib/openhab/dsl/rules/automation_rule.rb
  spec/openhab/dsl/rules/builder_spec.rb
Labels: enhancement

#130 Link to the github pages at the bottom of USAGE.md
  USAGE.md
Labels: documentation

#129 Fix Thing builder example
  lib/openhab/dsl/things/builder.rb
Labels: documentation

#128 Use the default cron handler in openHAB 4
  lib/openhab/dsl/rules/triggers/cron/cron.rb
  lib/openhab/dsl/rules/triggers/cron/cron_handler.rb
Labels: enhancement
