Repository openhab/openhab-jruby, pull requests merged in 2023-10, with the labels that each got.

#168 Semantics.add should raise an error if parent is invalid
  lib/openhab/core/items/semantics.rb
  spec/openhab/core/items/semantics_spec.rb
Labels: bug

#169 Avoid having lines with multiple split sentences
  USAGE.md
Labels: documentation

#171 Fix typo on Thing#channels return type
  lib/openhab/core/things/thing.rb
Labels: documentation

#174 Fix latitude/longitude/altitude getters on Location objects
  lib/openhab/core/types/point_type.rb
Labels: bug

#157 Allow updating things/items/sitemaps by recreating them
  lib/openhab/core/emulate_hash.rb
  lib/openhab/core/items/group_item.rb
  lib/openhab/core/items/item.rb
  lib/openhab/core/items/number_item.rb
  lib/openhab/core/items/registry.rb
  lib/openhab/core/registry.rb
  lib/openhab/core/sitemaps/provider.rb
  lib/openhab/core/things/links/provider.rb
  lib/openhab/core/things/registry.rb
  lib/openhab/core/things/thing.rb
  lib/openhab/dsl/items/builder.rb
  lib/openhab/dsl/sitemaps/builder.rb
  lib/openhab/dsl/things/builder.rb
  spec/openhab/core/items/registry_spec.rb
  spec/openhab/dsl/items/builder_spec.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
  spec/openhab/dsl/things/builder_spec.rb
Labels: enhancement

#176 Inspect the full details of Channel attributes
  lib/openhab/core/things/channel.rb
Labels: enhancement

#177 Refactor ChannelsArray lookup by channel id and uid
  lib/openhab/core/things/proxy.rb
  lib/openhab/core/things/thing.rb
  spec/openhab/core/things/thing_spec.rb
Labels: enhancement

#178 Support all attributes of channel builder
  lib/openhab/core/things/channel.rb
  lib/openhab/core/things/thing.rb
  lib/openhab/dsl/things/builder.rb
  spec/openhab/dsl/things/builder_spec.rb
Labels: enhancement

#181 Warn when creating a tag that already exists
  lib/openhab/core/items/semantics.rb
  spec/openhab/core/items/semantics_spec.rb
Labels: bug

#182 Fix ProfileCallback#handle_command when an item is linked to a different channel type
  lib/openhab/core/things/item_channel_link.rb
  lib/openhab/core/things/profile_callback.rb
  spec/openhab/dsl_spec.rb
Labels: bug

#180 Add Item.link, Item.unlink, and Item.links.clear to add/remove a link to a channel
  lib/openhab/core/items/item.rb
  lib/openhab/core/items/item_channel_links.rb
  lib/openhab/core/things/channel_uid.rb
  lib/openhab/dsl/items/builder.rb
  spec/openhab/core/items/item_spec.rb
Labels: enhancement

#184 Add ensure_states! and bang version of command shortcuts
  USAGE.md
  lib/openhab/core/items.rb
  lib/openhab/core/items/dimmer_item.rb
  lib/openhab/core/items/generic_item.rb
  lib/openhab/core/items/player_item.rb
  lib/openhab/core/items/rollershutter_item.rb
  lib/openhab/core/items/semantics/enumerable.rb
  lib/openhab/core/items/switch_item.rb
  lib/openhab/dsl.rb
  lib/openhab/dsl/items/ensure.rb
  spec/openhab/dsl/items/ensure_spec.rb
Labels: enhancement

#188 Rearrange ensure_states! doc for clarity
  lib/openhab/dsl.rb
Labels: documentation

#187 Infer accepted_item_type in ChannelBuilder
  lib/openhab/core/things/profile_callback.rb
  lib/openhab/dsl/things/builder.rb
  spec/openhab/dsl/things/builder_spec.rb
Labels: bug

#189 Allow configuring predefined channels in Thing builder
  lib/openhab/dsl/things/builder.rb
  spec/openhab/dsl/things/builder_spec.rb
Labels: bug
