Repository openhab/openhab-jruby, pull requests merged in 2023-09, with the labels that each got.

#135 Add examples for executing external commands
  docs/examples.md
Labels: documentation

#126 Fix item builder's group COUNT function
  lib/openhab/dsl/items/builder.rb
  spec/openhab/dsl/items/builder_spec.rb
Labels: bug

#127 Add group function #to_s and #inspect
  lib/openhab/core/items/group_function.rb
  lib/openhab/core/items/group_item.rb
  spec/openhab/core/items/group_item_spec.rb
Labels: enhancement

#115 Make Configuration objects more Ruby-like
  USAGE.md
  lib/openhab/core/configuration.rb
  lib/openhab/core/emulate_hash.rb
  lib/openhab/core/items/metadata/hash.rb
  lib/openhab/core/items/metadata/namespace_hash.rb
  lib/openhab/core/things/links/provider.rb
  lib/openhab/core/things/thing.rb
  lib/openhab/dsl/rules/rule_triggers.rb
  lib/openhab/dsl/things/builder.rb
  spec/openhab/core/configuration_spec.rb
Labels: documentation, enhancement

#131 Add event attributes for TimerEvent
  lib/openhab/core/events/abstract_event.rb
  lib/openhab/core/events/timer_event.rb
  spec/openhab/core/events/timer_event_spec.rb
Labels: enhancement

#137 Add `thing` parameter for ItemBuilder
  lib/openhab/dsl/items/builder.rb
  spec/openhab/dsl/items/builder_spec.rb
Labels: enhancement

#134 Add usage information for openhab transformations
  USAGE.md
Labels: documentation

#125 add item type predicates
  lib/openhab/core/items/group_item.rb
  lib/openhab/core/items/item.rb
  spec/openhab/core/items/color_item_spec.rb
  spec/openhab/core/items/contact_item_spec.rb
  spec/openhab/core/items/date_time_item_spec.rb
  spec/openhab/core/items/dimmer_item_spec.rb
  spec/openhab/core/items/group_item_spec.rb
  spec/openhab/core/items/image_item_spec.rb
  spec/openhab/core/items/location_item_spec.rb
  spec/openhab/core/items/number_item_spec.rb
  spec/openhab/core/items/player_item_spec.rb
  spec/openhab/core/items/rollershutter_item_spec.rb
  spec/openhab/core/items/string_item_spec.rb
  spec/openhab/core/items/switch_item_spec.rb
Labels: enhancement

#133 Support providing and accessing context in rules
  USAGE.md
  lib/openhab/core/rules/rule.rb
  lib/openhab/dsl.rb
  lib/openhab/dsl/rules/automation_rule.rb
  lib/openhab/dsl/thread_local.rb
  spec/openhab/dsl/rules/builder_spec.rb
  spec/openhab/dsl_spec.rb
Labels: enhancement

#140 Add unit conversion operator (|) to java.math.BigDecimal
  lib/openhab/core_ext/ruby/numeric.rb
  spec/openhab/core_ext/ruby/numeric_spec.rb
Labels: bug

#142 Fix defaults with cron fields `dow` and `dom`
  lib/openhab/dsl/rules/builder.rb
  lib/openhab/dsl/rules/triggers/cron/cron.rb
  spec/openhab/dsl/rules/builder_spec.rb
Labels: bug

#143 Support Ruby Range in cron fields
  lib/openhab/dsl/rules/builder.rb
  lib/openhab/dsl/rules/triggers/cron/cron.rb
  spec/openhab/dsl/rules/builder_spec.rb
Labels: enhancement

#146 Clarify the use of `at` trigger
  lib/openhab/dsl/rules/builder.rb
Labels: documentation

#147 Fix QuantityType arithmetic of mixed units
  lib/openhab/core/types/quantity_type.rb
  spec/openhab/core/types/quantity_type_spec.rb
  spec/openhab/dsl_spec.rb
Labels: bug

#139 Sitemap Builder
  .rubocop.yml
  USAGE.md
  lib/openhab/core/items/registry.rb
  lib/openhab/core/provider.rb
  lib/openhab/core/sitemaps/provider.rb
  lib/openhab/dsl.rb
  lib/openhab/dsl/sitemaps/builder.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: enhancement

#149 Use block's source location as timer's log identifier
  lib/openhab/core/timer.rb
Labels: enhancement

#150 Stringify keys in http headers
  lib/openhab/core/actions/http.rb
  spec/openhab/core/actions_spec.rb
Labels: enhancement

#151 Fix thermostate typos
  USAGE.md
  docs/conversions.md
  lib/openhab/core/sitemaps/provider.rb
Labels: documentation

#153 Fix bridge uid in example
  lib/openhab/dsl/things/builder.rb
Labels: documentation

#154 Remove link for thing that didn't get linkified
  USAGE.md
Labels: documentation

#158 Support expire configuration options in Item Builder
  lib/openhab/core/items/metadata/hash.rb
  lib/openhab/dsl/items/builder.rb
  spec/openhab/dsl/items/builder_spec.rb
Labels: enhancement

#162 Support removing custom semantic tags
  lib/openhab/core/items/semantics.rb
  spec/openhab/core/items/semantics_spec.rb
Labels: enhancement

#163 Fix entity lookup inside item builder's item block
  lib/openhab/dsl/items/builder.rb
  spec/openhab/dsl/items/builder_spec.rb
Labels: bug

#165 Verify item builder's `dimension`
  lib/openhab/dsl/items/builder.rb
  spec/openhab/dsl/items/builder_spec.rb
Labels: bug

#164 Fix a non-array passed to item's `groups` argument inside group block
  lib/openhab/dsl/items/builder.rb
  spec/openhab/dsl/items/builder_spec.rb
Labels: bug

#167 Add Thing#provider
  lib/openhab/core/things/thing.rb
  spec/openhab/core/things/thing_spec.rb
Labels: enhancement
