Repository openhab/openhab-jruby, pull requests merged in 2023-04, with the labels that each got.

#49 support ItemStateUpdatedEvent
  CHANGELOG.md
  lib/openhab/core/events/item_state_updated_event.rb
  spec/openhab/core/events/item_state_updated_event_spec.rb
  spec/openhab/dsl/rules/builder_spec.rb
Labels: bug

#50 fix formatted_state when state is nil
  CHANGELOG.md
  lib/openhab/core/items/generic_item.rb
  spec/openhab/core/items/item_spec.rb
Labels: bug

#57 Fix profile example
  lib/openhab/dsl.rb
Labels: documentation

#58 Fix DSL.provider doc
  lib/openhab/dsl.rb
Labels: documentation

#55 Semantic Tag improvements: support tag attributes, tag lookup, and adding tags
  lib/openhab/core/items/semantics.rb
  spec/openhab/core/items/semantics_spec.rb
Labels: enhancement

#59 Docs tweaks for Semantics
  lib/openhab/core/items/semantics.rb
Labels: documentation

#66 Avoid having to re-lookup Semantics::Property on every reference in 3.4.x
  lib/openhab/core/items/semantics.rb
Labels: bug

#67 Audio.play_sound called the wrong Java method
  lib/openhab/core/actions/audio.rb
Labels: bug
