Repository openhab/openhab-jruby, pull requests merged in 2024-01, with the labels that each got.

#210 Fix condition handling for colors and visibility in sitemap builder
  lib/openhab/core/sitemaps/provider.rb
  lib/openhab/dsl/sitemaps/builder.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: bug

#212 Support staticIcon and dynamic icon in sitemap
  lib/openhab/dsl/sitemaps/builder.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: enhancement

#211 Support Buttongrid in Sitemap Builder
  lib/openhab/dsl/sitemaps/builder.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: enhancement

#216 testing: load storage based type providers
  lib/openhab/osgi.rb
  lib/openhab/rspec/helpers.rb
  lib/openhab/rspec/mocks/abstract_storage_based_type_provider_wrapped_storage_service.rb
Labels: bug

#215 Add more helper methods to access linked channels
  lib/openhab/core/items/item.rb
  lib/openhab/core/things/item_channel_link.rb
  spec/openhab/core/items/item_spec.rb
Labels: enhancement

#217 ignore damaged bundle in rspec
  lib/openhab/rspec/karaf.rb
Labels: bug

#220 Make sitemap label a kwarg
  lib/openhab/core/sitemaps/provider.rb
  lib/openhab/dsl/sitemaps/builder.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: bug

#226 Add Enumerable#toggle to complement #on and #off
  lib/openhab/core/items/semantics/enumerable.rb
  spec/openhab/core/items/semantics_spec.rb
Labels: enhancement

#228 fix buttongrid example
  lib/openhab/dsl/sitemaps/builder.rb
Labels: documentation

#229 Fix sitemap builder proxy
  lib/openhab/dsl/sitemaps/builder.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: bug

#230 Support selecting multiple types of location and equipment
  lib/openhab/core/items/semantics.rb
  spec/openhab/core/items/semantics_spec.rb
Labels: enhancement

#232 Add support for icons in sitemap builder switch mappings
  lib/openhab/dsl/sitemaps/builder.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: enhancement

#240 Refactor item lookup to speed up item builder
  lib/openhab/core/entity_lookup.rb
  lib/openhab/core/items/registry.rb
Labels: bug

#243 Add NumericItem#nonzero?
  lib/openhab/core/items/numeric_item.rb
  spec/openhab/core/types/quantity_type_spec.rb
Labels: enhancement

#245 Fix dummy items when using sitemap proxy builder
  lib/openhab/core/sitemaps/provider.rb
  lib/openhab/dsl/sitemaps/builder.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: bug

#236 Add support for TimeSeries
  lib/openhab/core/events/item_time_series_updated_event.rb
  lib/openhab/core/items/generic_item.rb
  lib/openhab/core/profile_factory.rb
  lib/openhab/core/things/profile_callback.rb
  lib/openhab/core/types/time_series.rb
  lib/openhab/core_ext/java/instant.rb
  lib/openhab/dsl.rb
  lib/openhab/dsl/rules/builder.rb
  lib/openhab/dsl/rules/name_inference.rb
  lib/openhab/rspec/mocks/thing_handler.rb
  spec/openhab/core/types/time_series_spec.rb
  spec/openhab/dsl/rules/builder_spec.rb
  spec/openhab/dsl_spec.rb
Labels: enhancement

#247 change example to more easily understood "Downlights"
  docs/testing.md
Labels: documentation
