Repository openhab/openhab-jruby, pull requests merged in 2024-09, with the labels that each got.

#328 DateTimeType implements Java's Comparable in openHAB 4.3
  lib/openhab/core/types/date_time_type.rb
Labels: bug

#327 Sitemap updates not propagated to listeners
  lib/openhab/core/sitemaps/provider.rb
  spec/openhab/core/sitemaps/provider_spec.rb
Labels: bug

#329 Support space separator between date and time
  lib/openhab/core/items/date_time_item.rb
  lib/openhab/dsl.rb
  spec/openhab/core/items/date_time_item_spec.rb
Labels: enhancement

#330 Make all providers notify their listeners when the script is unloaded
  lib/openhab/core/provider.rb
  lib/openhab/core/sitemaps/provider.rb
Labels: bug

#331 Make DateTimeType.parse use the local timezone when a time-only string doesn't specify a tz
  lib/openhab/core/types/date_time_type.rb
  lib/openhab/dsl.rb
  spec/openhab/core/types/date_time_type_spec.rb
Labels: bug

#335 Allow literal states for sitemap visibility rules
  lib/openhab/dsl/sitemaps/builder.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: enhancement

#336 Move #items and #things to EntityLookup
  lib/openhab/core/entity_lookup.rb
  lib/openhab/dsl.rb
  spec/openhab/dsl/sitemaps/builder_spec.rb
Labels: enhancement

#333 Add `#time_only?` and `#offset` to TimerEvent
  lib/openhab/core/events/timer_event.rb
Labels: enhancement

#337 Fix timed command expire
  lib/openhab/dsl/items/timed_command.rb
  spec/openhab/dsl/items/timed_command_spec.rb
Labels: bug

#341 Add `#yesterday?`, `#today?`, and `#tomorrow?` to ZonedDateTime, Date, and Time classes.
  lib/openhab/core_ext/java/zoned_date_time.rb
  lib/openhab/core_ext/ruby/date.rb
  lib/openhab/core_ext/ruby/time.rb
  spec/openhab/core_ext/java/zoned_date_time_spec.rb
Labels: enhancement

#339 update notification doc links to point to current openHAB
  lib/openhab/core/actions/notification.rb
Labels: documentation
