Repository openhab/openhab-jruby, pull requests merged in 2025-04, with the labels that each got.

#401 Support `ItemStateUpdatedEvent#last_state_update` and `ItemStateChangedEvent#last_state_change`
  lib/openhab/core.rb
  lib/openhab/core/events/item_state_changed_event.rb
  lib/openhab/core/events/item_state_updated_event.rb
  spec/openhab/core/events/item_state_changed_event_spec.rb
  spec/openhab/core/events/item_state_updated_event_spec.rb
Labels: enhancement

#397 Add `GenericItem#was`, `#was?`, `#was_xxx?` predicates, document `Item#last_state`, `#last_state_change`, and `#last_state_update` methods
  lib/openhab/core.rb
  lib/openhab/core/items.rb
  lib/openhab/core/items/call_item.rb
  lib/openhab/core/items/color_item.rb
  lib/openhab/core/items/contact_item.rb
  lib/openhab/core/items/date_time_item.rb
  lib/openhab/core/items/dimmer_item.rb
  lib/openhab/core/items/generic_item.rb
  lib/openhab/core/items/image_item.rb
  lib/openhab/core/items/item.rb
  lib/openhab/core/items/location_item.rb
  lib/openhab/core/items/number_item.rb
  lib/openhab/core/items/persistence.rb
  lib/openhab/core/items/player_item.rb
  lib/openhab/core/items/rollershutter_item.rb
  lib/openhab/core/items/string_item.rb
  lib/openhab/core/items/switch_item.rb
  spec/openhab/core/items/item_spec.rb
Labels: enhancement

#431 Support passing timer objects to other scripts via shared_cache
  lib/openhab/core/timer.rb
  lib/openhab/core/value_cache.rb
  lib/openhab/dsl.rb
  spec/openhab/core/value_cache_spec.rb
Labels: enhancement

#433 Semantic Tags: add `subclasses:` parameter to allow exact match and exclude all subclasses of the given tags
  lib/openhab/core/items/semantics.rb
  spec/openhab/core/items/semantics_spec.rb
Labels: enhancement

#435 handle nil last_state for was_xx? predicate
  lib/openhab/core/items.rb
Labels: bug

#436 Resolve $terminal from $console
  .rubocop.yml
  lib/openhab/console.rb
  spec/spec_helper.rb
Labels: bug

#427 Document console commands and bundle_gemfile setting
  USAGE.md
Labels: documentation

#437 minor grammatical errors in console gem command
  USAGE.md
Labels: documentation

#429 Autoload builders (items, things, sitemaps, rules) and item metadata
  lib/openhab/core.rb
  lib/openhab/core/items/generic_item.rb
  lib/openhab/core/items/metadata.rb
  lib/openhab/core/items/metadata/namespace_hash.rb
  lib/openhab/core/items/registry.rb
  lib/openhab/dsl.rb
  lib/openhab/dsl/items/builder.rb
  lib/openhab/dsl/items/tags.rb
  lib/openhab/dsl/rules/builder.rb
  lib/openhab/dsl/rules/triggers.rb
  lib/openhab/dsl/things/builder.rb
Labels: enhancement

#459 Enhance flexibility of #points
  lib/openhab/core/items/semantics.rb
  spec/openhab/core/items/semantics_spec.rb
Labels: enhancement
